# Generated by Django 5.0.7 on 2024-07-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_company_remove_book_author_products_sales_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
